### ISSUE TITLE
Support for multiple recipients

### ISSUE THREAD

**Issue by skydiver** [DevINX/oc-contactus#2]
I've tested separating addresses with commas, semicolons, spaces and nothing works.

Thanks.-

**Comment by FelixINX** [comment]
Hi!

Give me 1 hour or two and I will post an update.

It should not be complicated.

Thanks for the suggestion!

**Comment by FelixINX** [comment]
Update : 
I looked at the code, and it will see the interface. For now, I invite you to modify the code yourself.
Just add a `to`, for example:

``` php
$message->replyTo(post('email'), post('name'))
                ->to(Settings::get('recipient_email'), Settings::get('recipient_name'))
                ->to('skydiver@github.com', 'Skydiver') // Email followed by name
                ->subject(Settings::get('subject'));
```

**Comment by skydiver** [comment]
Great tip.

Don't worry, it's just an enhancement, i'm not asking for ETA.

Thanks for your help.

**Comment by skydiver** [comment]
👋
