### ISSUE TITLE
version.yaml issue

### ISSUE THREAD

**Issue by keiosweb** [DevINX/oc-contactus#5]
Hello,

Thanks for the mention in update log, but the current form makes the migration crash on laravel5.5 version with:
![](https://i.keios.eu/jz/ffs-2017-10-02-15-19-06.png)

Debug shows this:
![](https://i.keios.eu/jz/ffs-2017-10-02-15-19-54.png)

Solution is very simple and I won't make PR as it only requires one character change from your side and you can probably do it in 10 seconds. In `version.yaml` you should change

```
    - New language : polish. 
```

into

```
    - New language - polish. 
```

and all will work without problems.

thanks!

**Comment by viamage** [comment]
no love for this? PR added.

**Comment by FelixINX** [comment]
Sorry didn't see that.
